name: Android CI

on: 
  workflow_dispatch:
  push:
    branches-ignore:
      - 'master'
      - 'CI_Build'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Get Latest Tag
      id: get_tag
      uses: oprypin/find-latest-tag@v1.1.1
      with:
        repository: zhanghai/MaterialFiles

    - name: Remove NONFREE
      run: |
        rm -rf app/src/main/java/me/zhanghai/android/files/nonfree
        find -type f -exec sed -i '/\/\/#ifdef NONFREE/,/\/\/#endif/d' {} +

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew assembleRelease lintVitalRelease

    - name: Rename apk
      run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/MaterialFiles-${{ steps.get_tag.outputs.tag }}.Sora-Editor.$(git rev-parse --short "$GITHUB_SHA").apk

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.${{ steps.get_tag.outputs.tag }}
        path: app/build/outputs/apk/release/
        retention-days: 10