name: Android CI

on: 
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: true
        show-progress: false
        repository: 'zhanghai/MaterialFiles'

    - name: Fetch Repository Commit Details
      id: GetCommit
      run: |
        Count=`curl -I -k "https://api.github.com/repos/zhanghai/MaterialFiles/commits?per_page=1" | sed -n '/^[Ll]ink:/ s/.*"next".*page=\([0-9]*\).*"last".*/\1/p'`
        echo "Count=$Count" >> $GITHUB_OUTPUT
        # echo Short_SHA=$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_OUTPUT

    - name: Update Build Configuration
      run: |
        sed -i "/resValue 'string', 'app_version'/i\        versionNameSuffix '.Î²'" app/build.gradle
        sed -i "s/signingConfig signingConfigs.release/signingConfig signingConfigs.debug/" app/build.gradle
        sed -i "s/        versionCode [0-9]*/        versionCode ${{steps.GetCommit.outputs.commitCount}}/" app/build.gradle

    - name: Delete Non-Free Software Code
      run: |
        rm -rf app/src/main/java/me/zhanghai/android/files/nonfree
        find -type f -exec sed -i '/\/\/#ifdef NONFREE/,/\/\/#endif/d' {} +

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
        gradle-version: release-candidate
        arguments: build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-output v.${{steps.GetCommit.outputs.commitCount}}
        path: app/build/outputs/apk/
        retention-days: 7